version: 2.0
jobs:
  unit:
    docker:
      - image: cimg/node:16.11
    steps:
      - run: node --version
      - run: npm --version
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm ci
      - run: npm test
  release:
    docker:
      - image: cimg/node:16.11
    steps:
      - checkout
      - run: npm ci
      - run: npm run semantic-release
workflows:
  version: 2
  build_and_test:
    jobs:
      - unit
      - release:
          context: dev-workflows-release
          requires:
            - unit
          filters:
            branches:
              only:
                - master
