name: Release MCP

on:
  workflow_dispatch: ~
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build
        working-directory: ./packages/jsondiffpatch
      - run: npm publish --provenance --access public
        working-directory: ./packages/diff-mcp
