name: Release MCP

on:
  workflow_dispatch: ~
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build
        working-directory: ./packages/jsondiffpatch
      - run: npm publish
        working-directory: ./packages/diff-mcp
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
